apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: book-admin-role
  namespace: bookstore-microservices
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources:
      - namespaces
      - endpoints
      - services
      - nodes
      - nodes/proxy
      - pods
      - configmaps
    verbs:
      - list
      - get
      - watch
