apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-microservices-domain-payment
  namespace: bookstore-microservices
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: book-admin
      containers:
        - name: payment
          image: zwb12580/bookstore-kubernetes-domain-payment
          ports:
            - name: http-server
              containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
